name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Disparar deploy no Render
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
